FROM openjdk:17

EXPOSE 8080

#ADD ./target/com.ecommerce.app-0.0.1-SNAPSHOT.jar /app/backend/target/ecommerce.jar

#ENTRYPOINT ["java", "-jar", "/app/backend/target/ecommerce.jar"]

ENTRYPOINT ["java", "-jar", "/app/backend/target/com.ecommerce.app-0.0.1-SNAPSHOT.jar"]
